### ISSUE TITLE
Validation of `loop` attribute

### ISSUE THREAD

**Issue by westonruter** [swissspidy/gutenberg-bento#1]
In regards to:

https://github.com/swissspidy/gutenberg-bento/blob/f21bc26af026161877a84c49ae2bcc0da6af992c/inc/class-amp-carousel-sanitizer.php#L55-L58

So the validator rules should be updated to allow an empty string or `'loop'`, right? And this would mean the same as `true`.

It looks like it can also be a comma-separated list of booleans: 

https://github.com/ampproject/amphtml/blob/c491d6f3e767a6749b4e2c003d926111922784b8/extensions/amp-base-carousel/validator-amp-base-carousel.protoascii#L70-L74

Interesting that this is not mentioned in the docs: https://amp.dev/documentation/components/amp-base-carousel/#loop

**Comment by swissspidy** [comment]
> So the validator rules should be updated to allow an empty string or `'loop'`, right? And this would mean the same as `true`.

Yep, basically just like how is already done for `amp-video` or `amp-carousel`:

https://github.com/ampproject/amphtml/blob/c491d6f3e767a6749b4e2c003d926111922784b8/extensions/amp-video/validator-amp-video.protoascii#L71-L74

https://github.com/ampproject/amphtml/blob/c491d6f3e767a6749b4e2c003d926111922784b8/extensions/amp-carousel/validator-amp-carousel.protoascii#L63-L66

> It looks like it can also be a comma-separated list of booleans:
> Interesting that this is not mentioned in the docs: amp.dev/documentation/components/amp-base-carousel/#loop

That's indeed interesting 🤔 

Looking at the tests for the component, here's how it's intended to be used:

```html
<amp-base-carousel width="4" height="3" auto-advance="(min-width: 800px) true, false">
</amp-base-carousel>
```

Sounds like I should just file a ticket to just make plain `loop` work as well, as it's really inconsistent with other components.

**Comment by swissspidy** [comment]
Reported at https://github.com/ampproject/amphtml/issues/35555

**Comment by swissspidy** [comment]
Keeping open to update this in the plugin once fixed

**Comment by westonruter** [comment]
I've got a pending spec update in the plugin which will eliminate the need for forcing the `loop` attribute to have a value: https://github.com/ampproject/amp-wp/pull/6530.
