### ISSUE TITLE
Enabling the Loop setting causes editor crash 

### ISSUE THREAD

**Issue by westonruter** [swissspidy/gutenberg-bento#3]
When I try enabling the Loop setting I'm getting an editor crash:

https://user-images.githubusercontent.com/134745/128260369-f93aa476-46f1-47fc-95cc-a0987e2621d4.mov

> Uncaught TypeError: Y.Fragment is not a function

I suppose this is was https://github.com/ampproject/amphtml/issues/35412 which is now fixed but not yet released?

**Comment by swissspidy** [comment]
> I suppose this is was ampproject/amphtml#35412 which is now fixed but not yet released?

Yup!
