### ISSUE TITLE
Explore distribution of custom element JS/CSS with the plugin

### ISSUE THREAD

**Issue by westonruter** [swissspidy/gutenberg-bento#5]
In order to avoid a hard dependency on a CDN, we should consider a configuration where the custom element JS and CSS is distributed with the plugin. In addition to quelling any privacy concerns about loading external assets (as have been raised with Google Fonts), this also will also ensure that the version of the component used in the editor matches the version used on the frontend: currently the plugin bundles the React component from npm, but loads the custom element from the CDN.

**Comment by swissspidy** [comment]
Might be difficult to get the same version for the custom element without it being distributed via npm.

**Comment by swissspidy** [comment]
It's probably something that's best done before plugin distribution:

1. Run `npm update` to ensure you're using the latest version
2. Download CSS & JS from CDN and put into the plugin
3. 🚢

**Comment by swissspidy** [comment]
Filed an issue here: https://github.com/ampproject/amphtml/issues/35554

**Comment by westonruter** [comment]
> It's probably something that's best done before plugin distribution:

Ah yes, exactly. I meant as part of the build step, not at runtime.

**Comment by swissspidy** [comment]
Just pushed some changes to the plugin to make use of the new self-hosting capabilities since there's been great progress on that from the AMP side.

Also caught up with all the component renaming etc. that happened.
