### ISSUE TITLE
Carousel buttons not working in AMP version

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/gutenberg-bento#6]
I noticed that the custom sanitizer doesn't correctly update the prev/next buttons, as it always adds the `on=""` attribute to the first `.gutenberg-bento-carousel-buttons__prev`/`gutenberg-bento-carousel-buttons__next` element in the whole page instead of the first element within the block.

I tried to fix this in 55e11da2dc3d62c38f93de02e7ad3d586a373d6c by passing the second `$contextNode` param to `$this->dom->xpath->query()`, but to no avail. It didn't change anything.

Relevant code:

https://github.com/swissspidy/gutenberg-bento/blob/55e11da2dc3d62c38f93de02e7ad3d586a373d6c/inc/class-amp-carousel-sanitizer.php#L64-L79

Screenshot:

![Screenshot 2021-08-19 at 18 52 35](https://user-images.githubusercontent.com/841956/130112105-ea22b4ff-10d5-429c-be55-b3d2f05c0bf4.png)

See that  the sanitizer added `tap:wp-block-gutenberg-bento-carousel-1.next()` to the first block's button instead of the second one.

`$this->dom->getElementId()` updates the correct carousel element, so it's really just  the XPath query that seems to be wrong — or I am just not using it correctly.

**Comment by swissspidy** [comment]
@westonruter Perhaps you can help me here?

**Comment by westonruter** [comment]
I think the thing that was missing was the use of `.` in the XPath query to indicate where the context node fits into the expression.
