### ISSUE TITLE
Uncaught ReferenceError: bent is not defined

### ISSUE THREAD

**Issue by westonruter** [swissspidy/gutenberg-bento#9]
When trying to build the plugin recently, I got a strange issue where the block didn't show up in the editor. I looked at the console and found an error:

![image](https://user-images.githubusercontent.com/134745/130152117-6d436cc2-9d4d-4b4d-a571-f649656eb16b.png)

There's this `bent` symbol that seems to be an error:

![image](https://user-images.githubusercontent.com/134745/130152199-d405012b-1c85-4982-9318-55d77b440cb3.png)

I ran a dev build and here's the error:

![image](https://user-images.githubusercontent.com/134745/130152277-f1a7af3f-71d9-4d09-b889-658c449183f2.png)

The error is coming from `webpack:///./node_modules/@ampproject/amp-base-carousel/dist/component-react.js`:

![image](https://user-images.githubusercontent.com/134745/130152363-6e41adf4-e98b-4c05-8603-ff4f84e5eca9.png)

I can see this `bent` symbol in the following files downloaded from npm:

```
@ampproject/amp-base-carousel/dist/component-react.module.js
@ampproject/amp-base-carousel/dist/component-preact.max.module.js
@ampproject/amp-base-carousel/dist/component-preact.max.js
@ampproject/amp-base-carousel/dist/component-react.js
@ampproject/amp-base-carousel/dist/component-preact.js
@ampproject/amp-base-carousel/dist/component-react.max.js
@ampproject/amp-base-carousel/dist/component-react.max.module.js
@ampproject/amp-base-carousel/dist/component-preact.module.js
```

**Comment by westonruter** [comment]
@caroqliu Is this a bug with npm publishing?

**Comment by swissspidy** [comment]
Yes it appears to be. I reported this earlier at https://github.com/ampproject/amphtml/issues/35741

**Comment by swissspidy** [comment]
This was fixed upstream
